const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('muesli', {
  startRecording: (meetingId) => ipcRenderer.invoke('rec:start', meetingId),
  sendChunk: (meetingId, track, int16) => ipcRenderer.send('rec:chunk', meetingId, track, int16),
  stopRecording: (meetingId) => ipcRenderer.invoke('rec:stop', meetingId),
  transcribe: (wavFile) => ipcRenderer.invoke('whisper:transcribe', wavFile),
  settings: () => ipcRenderer.invoke('settings:get'),
  saveSettings: (fields) => ipcRenderer.invoke('settings:set', fields),
  meetings: {
    list: () => ipcRenderer.invoke('meetings:list'),
    search: (q) => ipcRenderer.invoke('meetings:search', q),
    get: (id) => ipcRenderer.invoke('meetings:get', id),
    create: (fields) => ipcRenderer.invoke('meetings:create', fields),
    update: (id, fields) => ipcRenderer.invoke('meetings:update', id, fields),
    remove: (id) => ipcRenderer.invoke('meetings:delete', id),
    reveal: (id) => ipcRenderer.invoke('meetings:reveal', id),
    transcribe: (id) => ipcRenderer.invoke('meetings:transcribe', id),
    generate: (id) => ipcRenderer.invoke('meetings:generate', id),
  },
  templates: () => ipcRenderer.invoke('templates'),
  pullModel: (model) => ipcRenderer.invoke('models:pull', model),
  onProgress: (fn) => ipcRenderer.on('progress', (_e, id, p) => fn(id, p)),
  onPull: (fn) => ipcRenderer.on('pull', (_e, model, p) => fn(model, p)),
  modelInventory: () => ipcRenderer.invoke('models:inventory'),
  info: () => ipcRenderer.invoke('app:info'),
  autotest: !!process.env.MUESLI_AUTOTEST,
  autotestPlay: () => ipcRenderer.invoke('autotest:play'),
  autotestDone: (text) => ipcRenderer.send('autotest:done', text),
});
