const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('muesli', {
  startRecording: (meetingId) => ipcRenderer.invoke('rec:start', meetingId),
  sendChunk: (meetingId, track, int16) => ipcRenderer.send('rec:chunk', meetingId, track, int16),
  stopRecording: (meetingId) => ipcRenderer.invoke('rec:stop', meetingId),
  transcribe: (wavFile) => ipcRenderer.invoke('whisper:transcribe', wavFile),
  settings: () => ipcRenderer.invoke('settings:get'),
  saveSettings: (fields) => ipcRenderer.invoke('settings:set', fields),
  meetings: {
    list: () => ipcRenderer.invoke('meetings:list'),
    search: (q) => ipcRenderer.invoke('meetings:search', q),
    get: (id) => ipcRenderer.invoke('meetings:get', id),
    create: (fields) => ipcRenderer.invoke('meetings:create', fields),
    update: (id, fields) => ipcRenderer.invoke('meetings:update', id, fields),
    remove: (id) => ipcRenderer.invoke('meetings:delete', id),
    reveal: (id) => ipcRenderer.invoke('meetings:reveal', id),
    transcribe: (id) => ipcRenderer.invoke('meetings:transcribe', id),
    generate: (id) => ipcRenderer.invoke('meetings:generate', id),
    send: (id) => ipcRenderer.invoke('meetings:send', id),
    askAll: (history, question) => ipcRenderer.invoke('meetings:askAll', history, question),
    ask: (id, question) => ipcRenderer.invoke('meetings:ask', id, question),
    recap: (id, segments) => ipcRenderer.invoke('meetings:recap', id, segments),
    saveResult: (id, result) => ipcRenderer.invoke('meetings:saveResult', id, result),
    export: (id, kind) => ipcRenderer.invoke('meetings:export', id, kind),
    fix: (id, fix) => ipcRenderer.invoke('meetings:fix', id, fix),
    unfix: (id, index, change, never) => ipcRenderer.invoke('meetings:unfix', id, index, change, never),
  },
  words: { list: () => ipcRenderer.invoke('words:list'), add: (entry) => ipcRenderer.invoke('words:add', entry), remove: (entry) => ipcRenderer.invoke('words:remove', entry), pack: (name, on) => ipcRenderer.invoke('words:pack', name, on) },
  voices: { list: () => ipcRenderer.invoke('voices:list'), forget: (name) => ipcRenderer.invoke('voices:forget', name) },
  upcoming: () => ipcRenderer.invoke('calendar:upcoming'),
  pickAudio: () => ipcRenderer.invoke('audio:pick'),
  chooseRoot: () => ipcRenderer.invoke('data:chooseRoot'),
  templates: () => ipcRenderer.invoke('templates'),
  pullModel: (model) => ipcRenderer.invoke('models:pull', model),
  onProgress: (fn) => ipcRenderer.on('progress', (_e, id, p) => fn(id, p)),
  onLive: (fn) => ipcRenderer.on('live', (_e, id, segments) => fn(id, segments)),
  onAsk: (fn) => ipcRenderer.on('ask', (_e, id, token) => fn(id, token)),
  onTray: (fn) => ipcRenderer.on('tray', (_e, action) => fn(action)),
  openExternal: (url) => ipcRenderer.invoke('open:external', url),
  onPull: (fn) => ipcRenderer.on('pull', (_e, model, p) => fn(model, p)),
  modelInventory: () => ipcRenderer.invoke('models:inventory'),
  info: () => ipcRenderer.invoke('app:info'),
  platform: process.platform,
  autotest: !!process.env.MUESLI_AUTOTEST,
  autotestPlay: () => ipcRenderer.invoke('autotest:play'),
  autotestDone: (text) => ipcRenderer.send('autotest:done', text),
});
